spring:
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        boot:
          "[allow_jdbc_metadata_access]": "false"
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": "true"
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: "true"
  application:
    name: projeto
server:
  error:
    include-stacktrace: never
